# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.2
    hooks:
      - id: ruff-format
        exclude: ^src/insperion_api/migrations/versions
      - id: ruff-check
        args: [--select, I, --fix]
        exclude: ^src/insperion_api/migrations/versions