services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "8000:8000"
    # command:
    #   [
    #     "gunicorn",
    #     "insperion_api.main:app",
    #     "--workers=4",
    #     "--worker-class=insperion_api.workers.RestartableUvicornWorker",
    #     # "--worker-class=uvicorn.workers.UvicornWorker",  # Use this for production
    #     "--bind=0.0.0.0:8081",
    #     "--access-logfile=-",
    #     "--reload",
    #      "--log-level=debug"
    #   ]
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=debug
      - DB_USERNAME=username
      - DB_PASSWORD=username
      - DB_ENGINE=postgresql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=insperion_api
    depends_on:
      - db
      - minio
    volumes:
      - ./src/insperion_api:/insperion_api/src/insperion_api
      - ./tests:/insperion_api/tests

  db:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=insperion_api
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9002:9002"
      - "9003:9003"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password
    command: server --address :9002 --console-address :9003 /data

volumes:
  db:
  minio_storage: {}