"""Initial table structure

Revision ID: d78701aec560
Revises: 7386a75a8352
Create Date: 2025-11-06 23:56:45.211937

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd78701aec560'
down_revision: Union[str, None] = '7386a75a8352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_brand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='vehicle'
    )
    op.create_table('vehicle_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('year_launched', sa.Integer(), nullable=True),
    sa.Column('body_type', sa.String(length=64), nullable=True),
    sa.Column('seating_capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['vehicle.vehicle_brand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='vehicle'
    )
    op.create_table('vehicle_variant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('variant_name', sa.String(length=256), nullable=False),
    sa.Column('engine_type', sa.String(length=128), nullable=True),
    sa.Column('transmission', sa.String(length=64), nullable=True),
    sa.Column('fuel_type', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['vehicle.vehicle_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='vehicle'
    )
    op.create_table('vehicle_unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=128), nullable=False),
    sa.Column('psn', sa.String(length=128), nullable=True),
    sa.Column('chassis_no', sa.String(length=64), nullable=True),
    sa.Column('manufacturing_year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['vehicle.vehicle_variant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin'),
    schema='vehicle'
    )
    op.create_table('inspection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('flow_no', sa.String(length=64), nullable=False),
    sa.Column('inspection_type', sa.String(length=128), nullable=False),
    sa.Column('inspection_type_display_name', sa.String(length=512), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.vehicle_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='vehicle'
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_section', sa.Text(), nullable=False),
    sa.Column('config_key', sa.Text(), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=True),
    sa.Column('config_description', sa.Text(), nullable=True),
    sa.Column('is_exposable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='config'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config', schema='config')
    op.drop_table('inspection', schema='vehicle')
    op.drop_table('vehicle_unit', schema='vehicle')
    op.drop_table('vehicle_variant', schema='vehicle')
    op.drop_table('vehicle_model', schema='vehicle')
    op.drop_table('vehicle_brand', schema='vehicle')
    # ### end Alembic commands ###