"""Initial schema structure

Revision ID: 7386a75a8352
Revises: 
Create Date: 2025-11-06 23:56:18.938273

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7386a75a8352'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS config;")
    op.execute("CREATE SCHEMA IF NOT EXISTS vehicle;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SCHEMA IF EXISTS vehicle;")
    op.execute("DROP SCHEMA IF EXISTS config;")
    # ### end Alembic commands ###